### PR TITLE
Updated pubspec.yaml to newer resolvable versions

### PR DESCRIPTION
**Pull request by wibtu**
Hey guys,

could you use the newer version of device_info_plus? Checking it locally with pub outdated showed no errors.

Best wishes

### CODE REVIEW

**Comment by SergeShkurko** [comment]
@wibtu thanks for your contribution!

**Comment by ertgrulll** [comment]
@SergeShkurko can you please update pub package also?

**Comment by mreinfurt** [comment]
@SergeShkurko Just pushing this because it has been 3 weeks. A new release would be much appreciated! :)

**Comment by MadsStolt** [comment]
Any update here?

**Comment by albertolina** [comment]
can you publish the new release? :)

**Comment by tpouriel** [comment]
@SergeShkurko Please release the version to pub.dev 😇

**Pull request merged**
