### PR TITLE
Support Flutter 3.10.0 and Dart 3

### PR DESCRIPTION
**Pull request by ascendedco**

### CODE REVIEW

**Comment by ThomasAunvik** [comment]
Is this project no longer maintained anymore? Even #401 didn't get attention enough to be fixed.

And the latest release is 7 months ago.
image

Would it be needed to publish a fork of it?

**Comment by matejhocevar** [comment]
Thank you so much @ascendedco! 🙏🙏 Works wonders!

I hope you don't mind my fork, before this PR gets accepted, feel free to use the following:

```
  pdfx:
    git:
      url: https://github.com/matejhocevar/packages.flutter
      path: packages/pdfx
      ref: support-flutter-v3
```.

I merged @ascendedco PR and created a tag `support-flutter-v3`.

**Review by mzdm — APPROVED** [review]

**Review by hugobrancowb — APPROVED** [review]

**Comment by ascendedco** [comment]
> Thank you so much @ascendedco! 🙏🙏 Works wonders!
> 
> I hope you don't mind my fork, before this PR gets accepted, feel free to use the following:
> 
> ```
>   pdfx:
>     git:
>       url: https://github.com/matejhocevar/packages.flutter
>       path: packages/pdfx
>       ref: support-flutter-v3
> ```
> 
> I merged @ascendedco PR and created a tag `support-flutter-v3`.

No problem at all @matejhocevar

**Comment by SergeShkurko** [comment]
@ascendedco thanks for your contribution!

**Pull request merged**
