### PR TITLE
Add print quality to renderer

### PR DESCRIPTION
**Pull request by deakjahn**
An extra argument to ˙render()˙.

### CODE REVIEW

**Comment by SergeShkurko** [comment]
@deakjahn hello

can you provide an example / description of what it can be used for?

**Comment by deakjahn** [comment]
Yes. To render a PDF for printing. It depends on the native PdfRenderer and the Pdfium code behind it, but the bitmap it creates is supposedly slightly different from the bitmap created for display. I never checked the source code, frankly, but I think the difference is in how it handles aliasing of the edges. Printing has different requirements than displaying.

**Comment by deakjahn** [comment]
I checked in the meantime. FOR_DISPLAY uses LCD display specific aliasing techniques. This is clearly unwanted when rendering for print.

**Comment by SergeShkurko** [comment]
@deakjahn thanks for your contribution!

**Pull request merged**
