### PR TITLE
chore: updated device_info_plus version

### PR DESCRIPTION
**Pull request by vlazdra**
Updated the device info plus version since they did a major release. Not sure why they decided to do so, since the change itself is not that major.

Device info plus release notes here: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/device_info_plus/device_info_plus/CHANGELOG.md

### CODE REVIEW

**Comment by vlazdra** [comment]
Hey @SergeShkurko can you please take a look at this PR and do a merge and a release? Thank you.

**Comment by vlazdra** [comment]
Hey @SergeShkurko could you please take a look at the PR?

**Comment by SergeShkurko** [comment]
> Hey @SergeShkurko could you please take a look at the PR?

Yes, I could. Thanks for your contribution!

**Comment by vlazdra** [comment]
@SergeShkurko Can you please release this change in the next version?

**Comment by vlazdra** [comment]
Hey @vasilich6107 👋 

Unfortunately I'm not the developer of this package. That means that it's not up to me to release the change. 🫤

**Pull request merged**
