### PR TITLE
v2.7.0

### PR DESCRIPTION
**Pull request by emakar**
updated changelog with notable changes (actually all of the changes since 2.6.0 bump)

### CODE REVIEW

**Comment by emakar** [comment]
@SergeShkurko Hi! Could you please merge it and publish new version?

**Comment by stan-at-work** [comment]
Can someone finally push this to pub dev ....

**Comment by rivella50** [comment]
@emakar So we could temporarily also use your forked and updated 2.7.0 release?

**Comment by emakar** [comment]
> @emakar So we could temporarily also use your forked and updated 2.7.0 release? Would then be used like this i guess:
> 
> ```
> pdfx:
>     git:
>       url: https://github.com/emakar/packages.flutter.git
>       ref: 2.7.0
>       path: packages/pdfx/
> ```

yes

**Comment by SergeShkurko** [comment]
@emakar thanks for your contribution!

**Comment by stan-at-work** [comment]
Hes alive... 🥳

**Comment by moshe5745** [comment]
> > @emakar So we could temporarily also use your forked and updated 2.7.0 release? Would then be used like this i guess:
> > ```
> > pdfx:
> >     git:
> >       url: https://github.com/emakar/packages.flutter.git
> >       ref: 2.7.0
> >       path: packages/pdfx/
> > ```
> 
> yes

This one works.

But when I try to add the package with pub.dev it still falls with dependencies issue.
Did `flutter pub cache repair` + `flutter clean` before trying.

**Pull request merged**
