### PR TITLE
Update dependencies device_info_plus ^10.1.0

### PR DESCRIPTION
**Pull request by JosephNK**
I did update dependencies device_info_plus ^10.1.0.

### CODE REVIEW

**Comment by stan-at-work** [comment]
Can this be merged ?

**Comment by tologonkudaiberdiuulu** [comment]
@SergeShkurko please merge

**Comment by NeatFastro** [comment]
Any updates on this?

**Comment by SergeShkurko** [comment]
@JosephNK thanks for your contribution!

**Pull request merged**
