### PR TITLE
[pdfx] Migrate to package:web

### LINKED ISSUE #486: pdfx: Migrate to `package:web` to support WASM
The short version:
- Migrate usage of dart:html to package:web
- Migrate usage of dart:js, dart:js_util, and package:js to dart:js_interop

This will allow compiling to WASM engine instead of just JavaScript on web.

Full migration guide: https://dart.dev/interop/js-interop/package-web

### PR DESCRIPTION
**Pull request by koji-1009**
I migrated the code from package:js to package:web.
When running the example app on dart 3.3, the internet_file also needs to be dart 3.3 compliant, so I temporarily hide it from dependencies to check that it works.

Closes #486 #492 #501 #502

### CODE REVIEW

**Comment by SergeShkurko** [comment]
@koji-1009  Looks pretty. I will test it in details when conflict and review issue be resolved
Just notify me in telegram: http://t.me/serge_shkurko

**Comment by emakar** [comment]
@SergeShkurko everything seem to be resolved, we are waiting for this to be released so that we can upgrade device_info_plus (for privacy manifest purpose)

**Comment by NashIlli** [comment]
+1

**Comment by SergeShkurko** [comment]
@koji-1009 thanks for your contribution!

**Comment by emakar** [comment]
@SergeShkurko could you please release a new version?

**Comment by bloemy7** [comment]
A new version would be greatly appreciated @SergeShkurko ! Thanks a lot.

**Comment by ElecSmurf** [comment]
Hi, is there any update on this? Is there a perspective on a release that builds to wasm?

**Pull request merged**
